[tool.poetry]
name = "llmkira"
version = "0.25.4"
description = "A chain message bot based on OpenAI"
authors = ["llmkira <me@dianas.cyou>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://llmkira.github.io/Docs/"
repository = "https://github.com/LlmKira/Openaibot"
keywords = ["llmbot", "llmkira", "openai", "chatgpt", "telegram", "bot"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: MIT License",
]
packages = [{ include = "llmkira" }]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
pathlib = ">=1.0.1"
pydantic = { version = "^1.10.0", extras = ["dotenv"] }
loguru = ">=0.5.3"
httpx = "0.24.1"
socksio = "^1.0.0"
python-dotenv = "^1.0.0"
redis = ">=4.5.4"
aio-pika = "^9.3.0"
arclet-alconna = "^1.7.26"
shortuuid = "^1.0.11"
tiktoken = "^0.5.1"
nest-asyncio = "^1.5.8"
contextvars = "^2.4"
pytz = "^2023.3.post1"
numpy = "^1.26.0"
fasttext-wheel = "^0.9.2"
tenacity = "^8.2.3"
pysocks = "^1.7.1"
flask-sqlalchemy = "^3.1.1"
hikari = "^2.0.0.dev121"
hikari-crescent = "^0.6.4"
khl-py = "^0.3.16"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
